// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import { AppointmentProvider } from "@/context/AppointmentContext";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         <AppointmentProvider> {/* Wrap with Provider */}
// //           {children}
// //         </AppointmentProvider>
// //       </body>
// //     </html>
// //   );
// // }

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AppointmentProvider } from "@/context/AppointmentContext";
// import Navbar from "@/components/Navbar"; // ✅ Import Navbar


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Esthetix Dental",
//   description: "Clinic Management System",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <AppointmentProvider> {/* Wrap with Provider */}
//           <div className="h-screen flex flex-col">
//             <Navbar /> {/* ✅ Navbar stays fixed */}
//             <main className="flex-grow overflow-auto">{children}</main> {/* Page Content */}
//           </div>
//         </AppointmentProvider>
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppointmentProvider } from "@/context/AppointmentContext";
import { AuthProvider } from "@/context/AuthProvider"; // ✅ Add this
import Navbar from "@/components/Navbar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Esthetix Dental",
  description: "Clinic Management System",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <AuthProvider> {/* ✅ Wrap everything */}
        <AppointmentProvider>
            <div className="h-screen flex flex-col">
              <Navbar />
              <main className="flex-grow overflow-auto">{children}</main>
            </div>
            </AppointmentProvider>
            </AuthProvider>
      </body>
    </html>
  );
}
